owner: MrAmericanMike
repo: funkytown

sites:
  - name: MAM-Render
    url: https://mam.onrender.com/

status-website:
  baseUrl: /funkytown
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: FunkyTown
  introTitle:
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
