owner: MrAmericanMike
repo: funkytown

sites:
#  - name: Twitch·MrAmericanBot·Replit
#    url: https://TwitchBot.mramericanmike.repl.co
#  - name: Discord·MrAmericanBot·Replit
#    url: https://DiscordBot.mramericanmike.repl.co
#  - name: Discord·KoalaBot·Replit
#    url: https://KoalaBot.mramericanmike.repl.co
#  - name: Discord·CityGuessinBot·Replit
#    url: https://CityGuessin.mramericanmike.repl.co
#  - name: Discord·GeoBottr·Render
#    url: https://geobottr.onrender.com/
  - name: Render
    url: https://mam.onrender.com

status-website:
  theme: dark
  baseUrl: /funkytown
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: FunkyTown
  introTitle: "**FunkyTown**"
  introMessage: Monitoring bots
  navbar:
    - title: Status
      href: /$REPO
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/10 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
